@startuml
start

:Secretária acessa o sistema;
:Seleciona opção "Marcar Consulta";
:Informa dados do paciente;
:Seleciona dentista e horário;
if (Horário disponível?) then (Sim)
  :Consulta agendada;
  :Enviar mensagem de confirmação ao paciente;
else (Não)
  :Exibir mensagem de horário indisponível;
  :Solicitar novo horário;
endif

stop
@enduml