@startuml
start
:Dentista finaliza registro do atendimento;
:Solicita assinatura digital do dentista e paciente;
:Ambos assinam em dispositivo touch;
:Sistema registra assinaturas;
if (Assinatura pendente?) then (Sim)
  :Sistema registra motivo;
endif
stop
@enduml
