@startuml diagrama_casos_de_uso

skinparam packageStyle rectangle
skinparam handwritten false
skinparam shadowing false
skinparam linetype ortho
skinparam packageStyle folder
skinparam usecaseBorderThickness 1

skinparam Rankdir top to bottom
left to right direction

actor Secretaria as sec
actor Dentista as dent
actor Paciente as pac
actor Sistema as sys

package "Gerenciamento de Acesso" {
  usecase "UC1: Efetuar Login" as UC1
  usecase "Validar Credenciais" as valid_cred
  usecase "Carregar Permissões de Acesso" as def_perm
}
together {
  package "Gerenciamento de Agenda" {
    together {
      usecase "UC2: Visualizar Agenda Unificada" as UC2
      usecase "UC3: Visualizar Agenda Individual" as UC3
    }
    together {
      usecase "UC4: Marcar Consulta" as UC4
      usecase "UC5: Confirmar Horário Consulta" as UC5
    }
    together {
      usecase "UC7: Mudar Status Consulta" as UC7
      usecase "UC8: Enviar Mensagem Automática de Confirmação" as UC8
    }    
    together {
      usecase "UC14: Verificar Disponibilidade" as UC14
      usecase "UC15: Selecionar Sala" as UC15
    }
  }
}

together {
  package "Gerenciamento de Pacientes" {
    together {
      usecase "UC6: Atualizar Dados Paciente" as UC6
      usecase "UC12: Excluir Paciente" as UC12
    }
    together {
      usecase "UC13: Cadastrar Paciente" as UC13
      usecase "Validar CPF" as valid_cpf
    }
  }
}

together {

  package "Gerenciamento de Prontuários" {
    together {
      usecase "UC9: Consultar Prontuário Eletrônico" as UC9
      usecase "UC10: Assinar Prontuário" as UC10
    }    
    together {
      usecase "UC11: Registrar Valores Consultas" as UC11
      usecase "UC16: Anexar Documentos" as UC16
      usecase "UC17: Visualizar Histórico" as UC17
    }
  }
}

sec -[#blue]-> UC1
sec -[#blue]-> UC2
sec -[#blue]-> UC4
sec -[#blue]-> UC5
sec -[#blue]-> UC6
sec -[#blue]-> UC7
sec -[#blue]-> UC9
sec -[#blue]-> UC12
sec -[#blue]-> UC13

dent -[#green]-> UC1
dent -[#green]-> UC3
dent -[#green]-> UC7
dent -[#green]-> UC9
dent -[#green]-> UC10
dent -[#green]-> UC11

pac -[#red]-> UC5
pac -[#red]-> UC8

sys -[#gray]-> UC8

UC1 ...> valid_cred : <<include>>
UC1 ...> def_perm : <<include>>
UC4 ...> UC14 : <<include>>
UC4 ...> UC15 : <<include>>
UC4 ...> UC5 : <<include>>
UC6 ...> valid_cpf : <<include>>
UC9 ...> UC17 : <<include>>
UC13 ...> valid_cpf : <<include>>

UC7 .[#purple]> UC8 : <<extend>>
UC10 .[#purple]> UC9 : <<extend>>
UC11 .[#purple]> UC9 : <<extend>>
UC16 .[#purple]> UC9 : <<extend>>


@enduml
